name       = "formatmul"
version    = "VERSION"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright 2023, Seyed Ali Ghasemi"
license    = "LICENSE"

[preprocess]
[preprocess.cpp]
macros = []

[dependencies]
kinds   = {git="https://github.com/gha3mi/kinds.git"}
fortime = {git="https://github.com/gha3mi/fortime.git"}

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[[test]]
name       = "test1"
source-dir = "test"
main       = "test1.f90"

[[test]]
name       = "test2"
source-dir = "test"
main       = "test2.f90"


[[example]]
name       = "example1"
source-dir = "example"
main       = "example1.f90"

[[example]]
name       = "example2"
source-dir = "example"
main       = "example2.f90"


[[example]]
name       = "example3"
source-dir = "example"
main       = "example3.f90"

[[example]]
name       = "example4"
source-dir = "example"
main       = "example4.f90"
